# Generated by Django 3.1.3 on 2022-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Apellidos'),
        ),
    ]
