# Generated by Django 3.1.3 on 2022-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fichas', '0002_auto_20220413_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectores',
            name='codigo_inspector',
        ),
        migrations.AlterField(
            model_name='inspectores',
            name='ciudad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_fichas.ciudadcodigo'),
        ),
    ]
