# Generated by Django 3.1.3 on 2022-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fichas', '0003_auto_20220413_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectores',
            name='carnet_inspector',
            field=models.FileField(blank=True, default=None, upload_to='protected/certificados/'),
        ),
    ]
