# Generated by Django 3.1.3 on 2022-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fichas', '0005_auto_20220418_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposaccesoriometalicos',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='equiposarnes',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='equiposcascosegurida',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='equiposeslinga',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='equiposlineasanclajes',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='equipossillasperchas',
            name='fecha_puesta_en_uso',
            field=models.DateField(blank=True, default='2022-04-19'),
        ),
        migrations.AlterField(
            model_name='inspectores',
            name='fecha',
            field=models.DateField(blank=True, default='2022-04-19', verbose_name='Fecha del curso'),
        ),
    ]
